import { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto font
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/NextAyth";

const roboto = Roboto({
  subsets: ["latin"], 
  weight: ["400"], 
  variable: "--font-roboto", 
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: [ "300" ],
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <AuthProvider>
      <body className={`${poppins.className} ${poppins.variable}   antialiased`}>
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
